#SYNTAX TO CONNECT PYTHON WITH DATABASE.

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()

def BLACKHOLES_DIR():
  mycursor.execute("CREATE TABLE IF NOT EXISTS BLACKHOLES_DIR(\
      BLACKHOLE_NAME VARCHAR(60) PRIMARY KEY,\
      SIZE VARCHAR(60),\
      DISTANCE_FROM_NEAREST_CONSTELLATION VARCHAR(60),\
      MASS VARCHAR(60)\
      )")

#1
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('3C273','DIAMETER ROUGHLY SIZE OF OUR SOLAR SYSTEM','2 BILLION LIGHT-YEAR FROM VIRGO','1 BILLION SOLAR MASS')")
#2
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('ARP 151','DIAMETER ROUGHLY 30 TO 100 TIMES THE SIZE OF THE SUN','300 MILLION LIGHT-YEAR FROM URSA MAJOR','6.5 MILLION TO 20 MILLION SOLAR MASS')")
#3
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('IC 1459','DIAMETER ROUGHLY THE SIZE OF THE ORBIT OF JUPITER ','100 MILLION LIGHT-YEAR FROM GRUS','350 MILLION TO 2.5 BILLION SOLAR MASS')")
#4
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M104','DIAMETER LARGER THAN THE ORBIT OF SATURN','32 MILLION LIGHT-YEAR FROM VIRGO','660 MILLION SOLAR MASS')")
#5
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M105','LARGER THAN EARTH ORBIT','38 MILLION LIGHT-YEAR FROM LEO','60-200 MILLION SOLAR MASS')")
#6
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M106','GREATER THAN THE DISTANCE FROM EARTH TO SUN','24 MILLION LIGHT-YEAR FROM CANES VENATICI ','24-38 MILLION SOLAR MASS')")
#7
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M31','DIAMETER ROUGHLY EQUAL TO THE ORBIT OF VENUS','2.5 MILLION LIGHT-YEAR FROM ANDROMEDA','30 MILLION SOLAR MASS')")
#8
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M32','DIAMETER ABOUT 10 MILLION MILES','2.4 MILLION LIGHT-YEAR FROM ANDROMEDA','3 MILLION SOLAR MASS')")
#9
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M51','DIAMETER OF 4 MILLION MILES','27 MILLION LIGHT YEARS FROM CANES VENATICI','1 MILLION SOLAR MASS')")
#10
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M60','DIAMETER 45 BILLION MILES','51 MILLION LIGHT-YEARS FROM VIRGO','4.5 BILLION SOLAR MASS')")
#11
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M77','SMALLER THAN MERCURY ORBIT','50-60 MILLION LIGHT-YEARS FROM CETUS','15 MILLION SOLAR MASS')")
#12
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M81','DIAMETER 30 MILLION MILES','12 MILLION LIGHT-YEARS FROM URSA MAJOR','7 MILLION SOLAR  MASS')")
#13
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M84 ','DIAMETER EQUAL TO THE SIZE OF NEPTUNE ORBIT ','50 MILLION LIGHT-YEARS FROM VIRGO','1.5 BILLION SOLAR MASS')")
#14
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('M87','THREE TIMES THE DIAMETER OF PLUTO ORBIT','50 MILLION LIGHT-YEARS FROM VIRGO','6.6 BILLION SOLAR MASS')")
#15
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('MILKY WAY','DIAMETER ROUGHLY 15 MILLION MILES','27000 MILLION LIGHT-YEARS FROM SAGITTARIUS ','4.1 MILLION SOLAR MASS')")
#16
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 1023','ROUGHLY THE SIZE OF EARTH ORBIT','33 MILLION LIGHT-YEARS FROM PERSEUS','40-60 MILLION SOLAR MASS')")
#17
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 1194','DIAMETER LARGER THAN EARTH ORBIT','170 MILLION LIGHT-YEAR FROM CETUS','65 MILLION SOLAR MASS')")
#18
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 1277','11 TIMES THE DIAMETER OF NEPTUNE','220 MILLION LIGHT-YEAR FROM PERSEUS','17 BILLION SOLAR MASS')")
#19
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 1365','8 TIMES THE DIAMETER OF SUN','56 MILLION LIGHT-YEAR FROM FORNAX','2 MILLION SOLAR MASS')")
#20
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 2273','DIAMETER 2/3 THE DISTANCE BETWEEN MERCURY AND SUN','85 MILLION LIGHT-YEAR FROM LYNX','7.5 MILLION SOLAR MASS')")
#21
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 2778','SMALLER THAN MERCURY ORBIT','76 MILLION LIGHT-YEAR FROM LYNX','9-36 MILLION SOLAR MASS')")
#22
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 2787','DIAMETER ROUGHLY EQUAL TO EARTH ORBIT','24 MILLION LIGHT-YEAR FROM URSA MAJOR','36-45 MILLION SOLAR MASS')")
#23
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 2960','DIAMETER EQUAL TO DISTANCE BETWEEN SUN TO MERCURY','230 MILLION LIGHT-YEAR FROM HYDRA','11.5 MILLION SOLAR MASS')")
#24
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3115','DIAMETER EQUAL TO URANUS ORBIT','32 MILLION LIGHT-YEAR FROM SEXTANS','400 MILLION TO 2 BILLION SOLAR MASS')")
#25
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3245','DIAMETER ROUGHLY EQUAL TO THE DIAMETER OF JUPITER ORBIT','68 MILLION LIGHT-YEAR FROM LEO MINOR','160-260 MILLION SOLAR MASS')")
#26
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3377','AS SMALL AS VENUS ORBIT','33 MILLION LIGHT-YEAR FROM LEO ','30-120 MILLION SOLAR MASS')")
#27
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3384','DIAMETER ROUGHLY THE SIZE OF ORBIT OF MERCURY','38 MILLION LIGHT-YEAR FROM LEO','16 MILLION SOLAR MASS')")
#28
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3393','DIAMETER LARGER THAN ORBIT OF MERCURY','165 MILLION LIGHT-YEAR FROM HYDRA','31 MILLION SOLAR MASS')")
#29
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3516','SLIGHTLY LARGER THAN MERCURY ORBIT','120 MILLION LIGHT-YEAR FROM URSA MAJOR','23 MILLION SOLAR MASS')")
#30
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3585','DIAMETER LARGER THAN THE SIZE OF THE ORBIT OF JUPITER','70 MILLION LIGHT-YEAR FROM HYDRA','340 MILLION SOLAR MASS')")
#31
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3607','DIAMETER LARGER THAN THE SIZE OF THE ORBIT OF MARS ','65 MILLION LIGHT-YEAR FROM LEO','125 MILLION SOLAR MASS')")
#32
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3608','DIAMETER LESS THAN THE SIZE OF ORBIT OF JUPITER','75 MILLION LIGHT-YEAR FROM LEO','210 MILLION SOLAR MASS')")
#33
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3783','ABOUT HALG THE SIZE OF MERCURY ORBIT','130 MILLION LIGHT-YEAR FROM CENTAURUS','8-10 MILLION SOLAR MASS')")
#34
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3842','DIAMETER 6 TIMES THE NEPTUNE ORBIT','320 MILLION LIGHT-YEAR FROM LEO','9.7 BILLION SOLAR MASS')")
#35
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3862','---','260 MILLION LIGHT-YEAR FROM LEO','---')")
#36
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3945 ','DIAMETER ABOUT 0.5 OF THE MERCURY ORBIT','65 MILLION LIGHT-YEAR FROM URSA MAJOR','9 MILLION MASS')")
#37
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 3998','DIAMETER ROUGHLY THE JUPITER ORBIT','45 MILLION LIGHT-YEAR FROM URSA MAJOR','270-800 MILLION SOLAR MASS')")
#38
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4026','DIAMETER ROUGHLY THE SIZE THE ASTEROID BELT','50 MILLION LIGHT-YEAR FROM URSA MAJOR','210 MILLION SOLAR MASS')")
#39
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4061 ','DIAMETER AT LEAST EQUAL TO THE NEPTUNE ORBIT','325 MILLION LIGHT-YEAR FROM COMA BERENICS','1-9 BILLION SOLAR MASS')")
#40
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4151 ','DIAMETER EQUAL TO THE SIZE OF THE ORBIT OF SATURN','43 MILLION LIGHT-YEAR FROM LEO','45 MILLION SOLAR MASS')")
#41
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4178','SMALLER THAN THE SUN','55 MILLION LIGHT-YEAR ','<200000 SOLAR MASS')")
#42
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4253','DIAMETER ROUGHLY THE SIZE OF THE ORBIT OF MERCURY','170 MILLION LIGHT-YEAR FROM COMA BERENICS','20 MILLION SOLAR MASS')")
#43
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4261','DIAMETER RANGE BETWEEN SATURN AND NEPTUNE ORBIT','100 MILLION LIGHT-YEAR FROM VIRGO','500 MILLION TO 1.2 BILLION  SOLAR MASS')")
#44
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4335','DIAMETER ROUGHLY THE SIZE OF THE ORBIT OF MARS','215 MILLION LIGHT-YEAR FROM URSA MAJOR','100 MILLION SOLAR MASS')")
#45
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4342','DIAMETER EQUAL TO THE DIAMETER OF JUPITER ORBIT ','75 MILLION LIGHT-YEAR FROM VIRGO','300 MILLION SOLAR MASS')")
#46
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4388','DIAMETER ABOUT 3/4 OF THE DISTANCE FROM SUN TO MERCURY','62 MILLION LIGHT-YEAR FROM VIRGO','8.5 MILLION SOLAR MASS')")
#47
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4395','SLIGHTLY LARGER THAN THE SUN','14 MILLION LIGHT-YEAR FROM CANES VENATICI','360000 SOLAR MASS')")
#48
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4473','DIAMETER ROUGHLY EQUAL TO THE ASTEROID BELT','50 MILLION LIGHT-YEAR FROM VIRGO','ROUGHLY 100 MILLION SOLAR MASS')")
#49
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4486b','DIAMETER ROUGHLY EQUAL TO THE DIAMETER OF SATURN ORBIT ','55 MILLION LIGHT-YEAR FROM VIRGO','500 MILLION SOLAR MASS')")
#50
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4697','DIAMETER LARGER THAN THE SIZE OF ASTEROID BELT','40 MILLION LIGHT-YEAR FROM VIRGO','ROUGHLY 175 MILLION SOLAR MASS')")
#51
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 4889','DIAMETER ROUGHLY 6-17 TIMES THE SIZE OF THE ORBIT OF NEPTUNE','335 MILLION LIGHT-YEAR  FROM COMA BERENICES','')")
#52
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 541','---','216 MILLION LIGHT-YEAR FROM CETUS','---')")
#53
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 5576','DIAMETER ROUGHLY EQUAL TO THE OUTER EDGE OF ASTEROID BELT','90 MILLION LIGHT-YEAR FROM VIRGO','180 MILLION SOLAR MASS')")
#54
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 6240','DIAMETER ROUGHLY EQUAL TO THE DIAMETER OF URANUS ','320 MILLION LIGT-YEAR FROM OPHIUCHUS','870 MILLION TO 2 BILLION SOLAR MASS ')")
#55
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 7052','---','190 MILLION LIGHT-YEAR FROM VULPECULA','330 MILLION SOLAR MASS')")
#56
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 7457','ABOUT 15 TIMES THE DIAMETER OF SUN','43 MILLION LIGHT-YEAR FROM PRGASUS','2.1-4.6 MILLION SOLAR MASS ')")
#57
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('NGC 821','DIAMETER FROM ORBIT SIZE OF EARTH TO MARS','100 MILLION LIGHT-YEARS FROM ARIES','50 TO 100 MILLION SOLAR MASSES')")
#58
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('RX J1242-11','GREATER THAN SIZE OF ASTEROID BELT ','700 MILLION LIGHT-YEARS FROM VIRGO','100 MILLION SOLAR MASSES')")
#59
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('SDSS J0927','ROUGHLY EQUAL TO THE DIAMETER OF SATURN ORBIT','6.5 BILLION LIGHT-YEARS FROM LEO','600 MILLION SOLAR MASS')")
#60
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES_DIR (BLACKHOLE_NAME, SIZE, DISTANCE_FROM_NEAREST_CONSTELLATION, MASS) VALUES\
      ('ULASJ1120-0641','LARGER THAN DIAMETER OF ORBIT OF NEPTUNE','13 BILLION LIGHT-YEARS FROM LEO','2 BILLION SOLAR MASSES')")

  mydb.commit()

#END........