#SYNTAX TO CONNECT PYTHON WITH DATABASE.

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()

def blackholes():
  mycursor.execute("CREATE TABLE IF NOT EXISTS BLACKHOLES(\
      BLACKHOLE_NAME VARCHAR(40) PRIMARY KEY,\
      TYPE VARCHAR(40),\
      CONSTELLATION VARCHAR(40)\
      )")

#1
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('MANATEE NEBULA','---','AQUILA')")
#2
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('SS 433','STELLAR','AQUILA')")
#3
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('V1487 Aql','STELLAR','AQUILA')")
#4
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('W49B','---','AQUILA')")
#5
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('V821 ARA','STELLAR','ARA')")
#6
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('XTE J1650-500','STELLAR','ARA')")
#7
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('CXOU J132527','STELLAR','CENTAURUS')")
#8
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('CYGNUS X-1','STELLAR','CYGNUS')")
#9
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('CYGNUS X3','STELLAR','CYGNUS')")
#10
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('V404 CYG','STELLAR','CYGNUS')")
#11
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('LB-1','STELLAR','GEMINI')")
#12
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('IL LUPI','STELLAR','LUPUS')")
#13
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('V616 MON','STELLAR','MONOCEROS')")
#14
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('GU MUS','STELLAR','MUSCA')")
#15
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('V381 NOR','STELLAR','NORMA')")
#16
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('GREAT ANNIHILATOR','INTERMEDIATE','OPHIUCHUS')")
#17
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('MESSIER 15','INTERMEDIATE','PEGUSUS')")
#18
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('GRO J0422+32','STELLAR','PERSEUS')")
#19
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('HLX-1','INTERMEDIATE','PHOENIX')")
#20
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('SN 1997D','STELLAR','RECTICULUM')")
#21
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('GCIRS 13E','INTRMEDIATE','SAGITTARIUS')")
#22
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('SAGITTARIUS A*','SUPERMASSIVE','SAGITTARIUS')")
#23
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('V4641 SGR','STELLAR','SAGITTARIUS')")
#24
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('IGR J17091-3624','STELLAR','SCORPIUS')")
#25
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('V1033 SCO','STELLAR','SCORPIUS')")
#26
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('HR 6819','STELLAR','TELESCOPIUM')")
#27
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('M33 X-7','STELLAR','TRIANGULUM')")
#28
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('KV UMA','STELLAR','URSA MAJOR')")
#29
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('M82 X-1','INTERMEDIATE','URSA MAJOR')")
#30
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('SDSS J120136','DOUBLE','URSA MAJOR')")
#31
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('M87*','SMB','VIRGO')")
#32
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('PKS 1302-102','DOUBLE','VIRGO')")
#33
  mycursor.execute("INSERT IGNORE INTO BLACKHOLES (BLACKHOLE_NAME, TYPE, CONSTELLATION) VALUES\
      ('QZ VUL','STELLAR','VULPECULA')")

  mydb.commit()

#END........