#SYNTAX TO CONNECT PYTHON WITH DATABASE.

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()

def Candidates_sn():
 mycursor.execute("CREATE TABLE IF NOT EXISTS CANDIDATES_SN (\
      IDENTIFIER VARCHAR(50) PRIMARY KEY,\
      RIGHT_ASCENSION VARCHAR(50),\
      DECLINATION VARCHAR(50),\
      CONSTELLATION VARCHAR(50),\
      DISTANCE_LIGHT_YEARS VARCHAR(50),\
      SPECTRAL_CLASS VARCHAR(50),\
      POSSIBLE_SUPERNOVA_TYPE VARCHAR(50)\
      )")
      
#1     
 mycursor.execute("""INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('IK PEGASI','21H 26M 26.7S',"+19°\' ",'PEGASUS','154.4 ± 1.0','A8m:/DA','la')""")
#2
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('SPICA','13H 25M 11.6S','-11°09 40.8','VIRGO','250+14/-13','B1','---')")
#3
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('ALPHA LUPI','14H 41M 55.8S','-47°23 17','LUPUS','465+12/-11','B1.5','II')")
#4
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('ANTARES','16H 29M 24.5S','-26°25 55','SCORPIUS','554+113/-80','M1.5LAB-B','IIP')")
#5
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('BETELGEUSE','05H 55M 10.3S','07°24 25','ORION','720+160/-110','M2LAB','IIP')")
#6 
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('RIGEL','05h 14m 32.3','-08°12 06','ORION','1118+30/-28','B8la','IIP(pec?)')")
#7
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('GAMMA^2 VELORUM','08H 90M 32.0S','-47°20 12','VELA','1120+130/-100','WC8+O7.5III','IB/IC')")
#8
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('T CORONAE BOREALIS','15H 59M 30.2S','+27°55 13','CORONA BOREALIS','2690+110/-100','M3III/D','IA')")
#9
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('KPD 1930+2752','19H 32M 14.9S','+27°58 35','CYGNUS','2860+130/-120','SDB/D','IA')")
#10
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('RHO CASSIOPEIAE','23H 54M 23.0S','+57°29 58','CASSIOPEIA','3440+930/-610','G2IA0E','IIL')")
#11
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('VY CANIS MAJORIS','07H 22M 58.3S','-25°46 03','CANIS MAJOR','3930+420/-350','M5EIA','II')")
#12
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('IRAS 17163-3907','17H 19M 49.3S','-39°10 37.9','SCORPIUS','3930+990/-660','LATE B/EARLY A','II')")
#13
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('HD 168625','18H 21M 19.5S','-16°22 26','SAGITTARIUS','5250+600/-490','B6IA','II')")
#14
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('NML CYGNI','20H 46M 25.6S','+40°06 59.4','CYGNUS','5250+420/-360','M6I','II')")
#15
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('WR 142','20H 21M 44.34S','+37°22 30.4','CYGNUS','5380','WO2','IC,GRB LIKELY')")
#16
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('IRC +10420','19H 26M 48.1S','+11°21 17','AQUILA','5600+2200/-1200','F8LA+','IIB')")
#17
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('MU CEPHEI','21H 43M 30.5S','+5°46 48','CEPHEUS','5900+3400/-1600','M2IA','IIN/IIB')")
#18
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('RS OPHIUCHI','17H 50M 13.2S','-06°42 28','OPHIUCHUS','7380+1000/-790','M2III/D','IA')")
#19
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('WR 93B','17H 32M 03.31S','-35°04 32.7','SCORPIUS','7470','WO3','IC')")
#20
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('WR 2','01H 05M 23.03S','+60°25 18.9','CASSIOPEIA','7830','WN2-W','IB/IC,GRB LIKELY')")
#21
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('WR 102','17H 4M 47.54S','-26°10 26.8','SAGITTARIUS','8610','W02','IC')")
#22
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('ETA CARINAE','10H 45M 03.6S','-59°41 04','CARINA','8630+69/-68','LBV/O','IB,SLSN LIKELY')")
#23
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('HD 179821','19H 13M 58.6S','+00°07 32','AQUILA','10500+2100/-1500','G5IA','IIL')")
#24
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('T PYXIDIS','O9H 04M 41.4S','-32°22 48','PYXIS','10700+1700/-1300','---','IA')")
#25
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('WR 104','18H 02M 04.1S','-23°37 41','SAGITTARIUS','13400+9200/-3900','WC9d/O8','IB/IC WITH GRB?')")
#26
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('V445 PUPPIS','07H 37M 56.9S','-25°56 59','PUPPIS','16000+5200/-4600','---','IA')")
#27
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('WR 38','11H 05M 46.43S','-61°13 48.6','CARINA','19700','WC4','IC')")
#28
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('WR 30A','10H 51M 38.89S','-60°56 34.9','CARINA','21900','W04+05-5.5','IC')")
#29
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('SHER 25','11H 15M 07.8S','-61°15 17','CARINA','43500+5200/-4200','B1.5LAB','---')")
#30
 mycursor.execute("INSERT IGNORE INTO CANDIDATES_SN (IDENTIFIER, RIGHT_ASCENSION, DECLINATION, CONSTELLATION, DISTANCE_LIGHT_YEARS, SPECTRAL_CLASS, POSSIBLE_SUPERNOVA_TYPE) VALUES \
      ('U SCORPII','16H 22M 30.7S','-17° 52 42','SCORPIUS','64000+68000/-17000','---','LA')")
 
 mydb.commit()
 
#END........          