#SYNTAX TO CONNECT PYTHON WITH DATABASE

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()  

def directly_imaged_exoplanets():
  mycursor.execute("CREATE TABLE IF NOT EXISTS DIRECTLY_IMAGED_EXOPLANETS(\
      STAR VARCHAR(50) PRIMARY KEY,\
      EXOPLANET VARCHAR(50),\
      JUPITER_MASS VARCHAR(50),\
      JUPITER_RADIUS VARCHAR(50),\
      PERIOD VARCHAR(50),\
      OBSERVATION_SEP VARCHAR(50),\
      ECCENTRICITY VARCHAR(50),\
      DISTANCE_TO_EARTH VARCHAR(50),\
      YEAR_OF_DISCOVERY VARCHAR(50),\
      IMAGING_TECHNIQUE VARCHAR(50)\
      )")
#1
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ('ALPHA CENTAURI' ,'---' ,'0.11±0.05' ,'0.459±0.17' ,'1' ,'1.1' ,'---' ,'4.37' ,'2021' ,'---')")
#2
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'AF Leporis' ,'AF Lep b' ,'2-5.5' ,'---' ,'20.6' ,'8' ,'0.47' ,'87' ,'2023' ,'DIRECT IMAGING')")
#3     
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'BETA PICTORIS','Beta Pictoris b' ,'2.7±0.3' ,'1.5±0.2' ,'22.47+3.77/-2.26' ,'9' ,'0.08+0.09/-0.05' ,'63.4±0.1' ,'2008' ,'RSDI')")
#4      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( '51 ERIDANI' ,'51 ERIDANI b' ,'2.6' ,'1.0' ,'?' ,'13' ,'?' ,'96' ,'2014' ,'ADI KLIP')")
#5  
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HR 8799' ,'HR 8799 E' ,'7.0' ,'1.3' ,'49' ,'14.5' ,'0.14' ,'128' ,'2010' ,'ADI KLIP')")
#6
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HR 8799' ,'HR 8799 D' ,'7.0' ,'1.3' ,'100' ,'24.5' ,'0.09' ,'128' ,'2008' ,'ADI LOCI')")
#7
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HR 8799' ,'HR 8799 C' ,'7.0' ,'1.3' ,'189' ,'37.4' ,'0.24' ,'128' ,'2008' ,'ADI LOCI')") 
#8
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HR 8799' ,'HR 8799 B' ,'5.0' ,'1.2' ,'474' ,'69.2' ,'0.17' ,'128' ,'2008' ,'ADI LOCI')")    
#9      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( '2M JO441444' ,'2M JO44144' ,'5-10' ,'---' ,'---' ,'15' ,'---' ,'456' ,'2010' ,'DIRECT IMAGING')")      
#10      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( '29 CYGNI' ,'HIP 99770 B' ,'13.9-16.1' ,'1.05' ,'51.0' ,'16.9' ,'0.25' ,'130.9' ,'2022' ,'ALOCI')")      
#11     
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'PDS 70' ,'PDS 70B' ,'?' ,'?' ,'---' ,'21' ,'---' ,'370' ,'2018' ,'ADI,TLOCI')")      
#12     
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'PDS 70' ,'PDS 70C' ,'?' ,'?' ,'---' ,'35' ,'---' ,'370' ,'2019' ,'SDI')")
#13      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HD 169142' ,'HD 169142 B' ,'1-4' ,'---' ,'---' ,'37.2' ,'---' ,'115' ,'2019/2023' ,'PSEUDO-ASDI,ADI')")   
#14      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( '2M1207' ,'2M1207B' ,'4.2' ,'1.5' ,'1620' ,'40.6' ,'0.37' ,'170' ,'2004' ,'DIRECT IMAGING')") 
#15
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( '59 VIRGINS' ,'GLIESE 504 B' ,'---' ,'?' ,'?' ,'43.5' ,'?' ,'57.27' ,'2013' ,'ADI,LOCI')")
#16      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'KAPPA' ,'KAPPA B' ,'---' ,'?' ,'242-900' ,'55' ,'0.69-0.85' ,'168.0' ,'2013' ,'ADI,LOCI')")  
#17      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HD 95086' ,'HD 95086 B' ,'5.0' ,'?' ,'?' ,'56' ,'?' ,'295' ,'2013' ,'ADI,LOCI')")         
#18      
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HIP 65426' ,'HIP 65426B' ,'6-12' ,'1.5' ,'600' ,'92' ,'' ,'363' ,'2017' ,'ADI,TLOCI')")                          
#19
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'AB AURIGAE' ,'AB AURIGAE B' ,'9-12' ,'2.75' ,'?' ,'93' ,'0.19-0.60' ,'508' ,'2022' ,'ADI/RSDI,ALOI')")
#20
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'VHS 1256-1257' ,'VHS 1256 B' ,'11.2' ,'---' ,'3900' ,'102' ,'---' ,'40' ,'2015' ,'DIRECT IMAGING')")
#21
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'FORMAHAUT' ,'FORMALHAUT B' ,'<2.0','---' ,'872-2000' ,'116.0' ,'---' ,'25' ,'2008/2012' ,'RSDI')")
#22
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'ROXs 42B' ,'ROXs 42B' ,'9±3' ,'2.5' ,'1968.3' ,'157' ,'UNKNOWN' ,'440±16' ,'2013' ,'DIRECT IMAGING')")
#23
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'FW TAURI' ,'FW TAURI B' ,'10±4' ,'?' ,'~12,000' ,'330' ,'?' ,'472.93' ,'2013' ,'DIRECT IMAGING')")
#24
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( '1RXS J1609' ,'1RXS 1609 B' ,'8-14' ,'1.7' ,'6518' ,'331.1' ,'0.08' ,'470' ,'2008' ,'DIRECT IMAGING')")
#25
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HD 203030' ,'HD 203030 B' ,'11+4/-3' ,'---' ,'---' ,'487' ,'---' ,'128' ,'2006' ,'SDI')")
#26
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'HD 106906' ,'HD 106906 B' ,'11±2' ,'?' ,'?' ,'650' ,'?' ,'300' ,'2013' ,'ADI')")
#27
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'DT VIRGINIS' ,'ROSS 458(AB)' ,'8.5' ,'1.8' ,'33.081' ,'1167.7' ,'0.17' ,'38' ,'2011' ,'DIRECT IMAGING')")
#28
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'BD+60 1417' ,'BD+60 1417 B' ,'15±5' ,'1.31±0.06' ,'---' ,'1662' ,'---' ,'144±13' ,'2021' ,'DIRECT IMAGING')")
#29
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'GU PISCIUM' ,'GU PISCIUM B' ,'11±2' ,'---' ,'163,000' ,'2000' ,'---' ,'155' ,'2014' ,'DIRECT IMAGING')")
#30 
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'WD 0806-661' ,'WD 0806-661 B' ,'7-9' ,'?' ,'?' ,'2500' ,'?' ,'62' ,'2011' ,'DIRECT IMAGING')")
#31
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'L 34-26' ,'COCONUTS-2B' ,'6.3+1.5/-1.9' ,'1.1±0.03' ,'~1,100,000' ,'6471' ,'---' ,'35.51±0.01' ,'2021/2011' ,'DIRECT IMAGING')")
#32
  mycursor.execute("INSERT IGNORE INTO DIRECTLY_IMAGED_EXOPLANETS (STAR ,EXOPLANET ,JUPITER_MASS ,JUPITER_RADIUS ,PERIOD ,OBSERVATION_SEP ,ECCENTRICITY ,DISTANCE_TO_EARTH ,YEAR_OF_DISCOVERY ,IMAGING_TECHNIQUE) VALUES\
      ( 'TYC 9486-927-1' ,'2MASS J2126-8140' ,'13.3±1.7' ,'?' ,'~900,000' ,'6684' ,'?' ,'80.72±13.86' ,'2016/2006' ,'DIRECT IMAGING')")

  mydb.commit()    