#SYNTAX TO CONNECT PYTHON WITH DATABASE

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()

def exoplanet_nearest():
  mycursor.execute("CREATE TABLE IF NOT EXISTS EXOPLANET_NEAREST(\
      NAME VARCHAR(40) PRIMARY KEY,\
      DISTANCE_FROM_EARTH VARCHAR(40),\
      APPARENT_MAGNITUDE VARCHAR(40),\
      SOLAR_MASS VARCHAR(40)\
      )")
#1
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('SUN','16x10^-6','-26.7','1')")
#2
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('PROXIMA CENTAURI','4.2465','11.13','0.123')")       
#3
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('LALANDE 21185','8.304','7.52','0.46')") 
#4
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('EPSILOM ERIDANI','10.489','3.73','0.781')")
#5 
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('LACAILLE 9352','10.724','7.34','0.489')")
#6 
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('ROSS 128','11.007','11.1','0.168')")
#7
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GROOMBRIDGE 34 A','11.619','8.1',	'0.38')")
#8
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('EPSILON INDI A','11.867','4.83','0.762')")
#9
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('TAU CETI','11.912','3.50','0.78')")
#10
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GJ 1061','11.984','7.52','0.113')")
#11
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('YZ CETI','12.122','12.1','0.130')")
#12
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('LUYTEN STAR','12.348','11.94','0.29')")
#13
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('TEEGARDEN STAR','12,497','15.40','0.08')")
#14
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('WOLF 1061','14.050','10.1','0.25')")
#15
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('TZ ARIETIS','14.578','12.30','0.14')")
#16
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 687','14.839','9.15','0.41')")
#17
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 674','14.849','9.38','0.35')")
#18
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 876','15.238','10.2','0.33')")
#19
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GJ 1002','15.806','13.84','0.12')")
#20
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('Gliese 832','16.200','8.67','0.45')")
#21
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GJ 3323','17.531','12.2','0.164')")
#22
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 251','18.215','9.65','0.372')")
#23
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 229 A','18.791','8.14','0.58')")
#24
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 752 A','19.292','9.13','0.46')")
#25
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('82 G. ERIDANI','19.704','4.26','0.85')")
#26
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('EQ PEGASI A','20.400','10.38','0.436')")
#27
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 581','20.549','10.5','0.31')")
#28
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 338 B','20.658','7.0','0.64')")
#29
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 625','21.131','10.2','0.30')")
#30
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('HD 219134','21.336','5.57','0.78')")
#31
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('LTT 1445 A','22.387','10.53','0.26')")
#32
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 393','22.953','8.65','0.41')")
#33
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 667 C','23.623','10.2','0.33')")
#34
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 514',' 24.878','9.03','0.53')")
#35
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 486','26.351','11.395','0.32')")
#36
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 686','26.613','9.58','0.42')")
#37
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('61 VIRGINIS','27.836','4.74','0.95')")
#38
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('CD CETI','28.052','14.001','0.161')")
#39
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 78','28.739','6.13','0.78')")
#40
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 849','28.750','10.4','0.49')")
#41
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 433','29.605','9.79','0.48')")
#42
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('HD 102365 A','30.396','4.89','0.85')")
#43
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 367','30.719','9.98','0.45')")
#44
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 357','30.776','10.9','0.34')")
#45
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 176','30.937','10.1','0.45')")
#46
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GJ 3512','30.976','13.11','0.123')")
#47
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('WOLF 1069','31.229','8.63','0.167')")
#48
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('AU MICROSCOPII','31.683','8.63','0.50')")
#49
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 436','31.882','10.67','0.41')")
#50
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('GLIESE 49','32.158','8.9','0.57')")
#51
  mycursor.execute("INSERT IGNORE INTO EXOPLANET_NEAREST(NAME, DISTANCE_FROM_EARTH, APPARENT_MAGNITUDE, SOLAR_MASS) VALUES\
      ('HD 260655','32.608','9.77','0.439')")

  mydb.commit() 

#THE END........