#SYNTAX TO CONNECT PYTHON WITH DATABASE.

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()

#UDF FOR THE TABLE (MOONS OF NEPTUNE)

def neptune_moons():
    mycursor.execute("CREATE TABLE IF NOT EXISTS neptune_moons(\
                  NAME VARCHAR(50) PRIMARY KEY, \
                  ABS_MAGN VARCHAR(50),\
                  DIAMETER VARCHAR(50), \
                  MASS VARCHAR(50), \
                  SEMIMAJOR_AXIS VARCHAR(50),\
                  ORBITAL_PERIOD VARCHAR(50),\
                  ORBITAL_INCLINATION VARCHAR(50),\
                  ECCENTRICITY VARCHAR(50),\
                  DISCOVERY_YEAR VARCHAR(50),\
                  DISCOVERER VARCHAR(50))")

#1
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('TRITON','-1.2','2705.2±4.8','2 139 000','354 759','-5.8769','156.865','0.0000','1846','Lassell')")
#2
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('NEREID','4.4','357 ± 13','≈2400','5 504 000','+360.14','5.8','0.749','1949','Kuiper')")
#3
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('NAIAD','9.6','60.4','≈13','48 224','+0.2944','4.691','0.0047','1989','Voyager Science Team')")
#4
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('THALASSA','8.7','81.4','≈35','50 074','+0.3115','0.135','0.0018','1989','Voyager Science Team')")
#5
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('DESPINA','7.3','156','≈170','52 526','+0.3346','0.068','0.0004','1989','Voyager Science Team')")
#6
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('GALATEA','7.2','174.8','≈280','61 953','+0.4287','0.034','0.0001','1989','Voyager Science Team')")
#7
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('LARISSA','6.8','194','≈380','73 548','+0.5555','0.205','0.0012','1981','Reitsema et al')")
#8
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('PROTEUS','5.0','420','≈3900','117 646','+1.1223','0.075','0.0005','1989','Voyager Science Team')")
#9
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('HALIMEDE','10.0','≈62','≈12','16 590 100','-1 879.30','113.1','0.286','2002','Holman et al')")
#10
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('PSAMATHE','11.0','≈40','≈2.9','47 611 900','-9 149.87','126.6','0.417','2003','Sheppard et al')")
#11
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('SAO','11.1','≈44','≈3.4','22 239 300','+2918.70','53.3','0.148','2002','Holman et al')")
#12
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('LAOMEDEIA','10.8','≈42','≈3.4','23 502 300','+3 175.65','37.7','0.409','2002','Holman et al')")
#13
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('NESO','10.7','≈60','≈11','49 871 600','-9 796.67','126.9','0.400','2002','Holman et al')")
#14
    mycursor.execute("INSERT IGNORE INTO neptune_moons(NAME, ABS_MAGN, DIAMETER, MASS, SEMIMAJOR_AXIS, ORBITAL_PERIOD, ORBITAL_INCLINATION, ECCENTRICITY, DISCOVERY_YEAR, DISCOVERER) VALUES\
      ('HIPPOCAMP','10.5','34.8±4.0','≈2.2','105 283','+0.9500','0.064','0.0005','2013','Showalter et al')")

    mydb.commit()

#END...