#SYNTAX TO CONNECT PYTHON WITH DATABASE.

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()

def MOST_MASSIVE_ASTR():
    mycursor.execute("CREATE TABLE IF NOT EXISTS MOST_MASSIVE_ASTR(\
     NAME VARCHAR(50) PRIMARY KEY,\
     MASS VARCHAR(20),\
     PRECISION_VALUE VARCHAR(20),\
     APPROX_PROPORTION_OF_ALL_ASTR VARCHAR(15))")
    
#1    
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('1 CERES','938.35 ','0.001%','39.2%')")
#2   
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('4 VESTA','259.076','0.0004%','10.8%')")
# 3  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('2 PALLAS','204','1.5%','8.5%')")
# 4  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('10 HYGIEA','87','8%','3.6%')")
# 5  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('704 INTERAMNIA','35','14%','1.5%')")
# 6  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('15 EUNOMIA','30','6%','1.3%')")
# 7  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('3 JUNO','27','9%','1.1%')")
# 8  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('511 DAVIDA','27','27%','1.1%')")
# 9  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('52 EUROPA','24','16%','1%')")
# 10  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('16 PSYCHE','23','13%','1%')")
# 11  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('532 HRCULINA','≈23','?','≈1%')")
# 12  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('31 EUPHROSYNE','17','18%','0.7%')")
# 13  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('65 CYBELE','15','12%','0.6%')")
# 14  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('87 SYLVIA','14.76','0.4%','0.6%')")
# 15  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('7 IRIS','14','17%','0.6%')")
# 16  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('29 AMPHITRITE','13','16%','0.5%')")
# 17  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('6 HEBE','12','20%','0.5%')")
# 18  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('88 THISBE','12','20%','0.5%')")
# 19  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('107 CAMILLA',' 11.2','1%','0.5%')")
# 20  
    mycursor.execute("INSERT IGNORE INTO MOST_MASSIVE_ASTR(NAME,MASS,PRECISION_VALUE,APPROX_PROPORTION_OF_ALL_ASTR)\
    VALUES('324 BAMBERGA','10','9%','0.4% ')")

    mydb.commit()             

#END .....