import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")

mycursor = mydb.cursor()

def protoplanetary_nebulae():
   mycursor.execute("CREATE TABLE IF NOT EXISTS PROTOPLANETARY_NEBULA(\
   NAME VARCHAR (20) PRIMARY KEY,\
   NGC VARCHAR(50),\
   OTHER_DESIGNATION VARCHAR(50),\
   DATE_DISCOVERED VARCHAR(50),\
   DISTANCE VARCHAR(50))")

#1
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('BOOMERANG NEBULA','---','CENTAURUS BIPOLAR NEBULA','---','ABOUT 5000')")
# 2
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('CALABASH NEBULA','---','OH231.8+4.2','---','ABOUT 4200')")
# 3
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('EGG NEBULA','---','CRL 2688','1996','ABOUT 3000')")
# 4
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('FROSTY LEO NEBULA','---','IRAS 09371+1212','---','ABOUT 3000')")
# 5 
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('RED RECTANGULAR NEBULA','---','HD 44179','1973','2300±300')")
# 6
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('COTTON CANDY NEBULA ','---','IRAS 17150-3224','---','---')")
# 7
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('WATER LILY NEBULA','---','IRAS 16594-4656','---','---')")
# 8
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('NO NAME-1','---','IRAS 22036+5306','---','---')")
# 9
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('WESTBROOK NEBULA','---','IRAS 04395+3601','---','--')")
# 10
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('NO NAME-2','---','IRAS 13208-6020','---','---')")
# 11
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('NO NAME-3','---','IRAS 20068+4051','---','---')")
# 12
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('LL Pegasi','---','IRAS 23166+1655','---','---')")
# 13
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('M1-92','---','IRAS 19343+2926','---','About 8000')")
# 14
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('NO NAME-4','---','IRAS 19024+0044','---','About 11000')")
# 15
   mycursor.execute("""INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES("Minkowski's Butterfly",'---','M2-9','---','About 2100')""")
# 16
   mycursor.execute("INSERT IGNORE INTO PROTOPLANETARY_NEBULA(NAME,NGC,OTHER_DESIGNATION,DATE_DISCOVERED,DISTANCE)\
    VALUES('Roberts 22(MR 22)','---','AFGL 4104','---','---')")

   mydb.commit()

#END......