#SYNTAX TO CONNECT PYTHON WITH DATABASE.

import mysql.connector 

mydb = mysql.connector.connect(
      host="localhost",
      user="root",
      password="qwerty0987",
      database="stellar_archive")           

mycursor = mydb.cursor()

#UDF FOR THE TABLE (SUPERNOVAS)

def SUPERNOVAS():
  mycursor.execute("CREATE TABLE IF NOT EXISTS SUPERNOVAS (\
        SUPERNOVA_DESIGNATION VARCHAR(50) PRIMARY KEY,\
        CONSTELLATION_NAME VARCHAR(50), FOREIGN KEY(CONSTELLATION_NAME) REFERENCES CONSTELLATIONS(NAME),\
        APPARENT_MAGNITUDE VARCHAR(50),\
        DISTANCE_IN_LIGHTYEARS VARCHAR(50),\
        TYPE VARCHAR(50),\
        GALAXY VARCHAR(80)\
        )")
        
#1
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 185','CENTAURUS','-4','9100','la','MILKY WAY')")
#2
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 386','SAGITTARIUS','+1.5','14700','II','MILKY WAY')")
#3
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 393','SCORPIUS','0','3400','II/IB','MILKY WAY')")
#4
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1006','LUPUS','-7.5','7200','la','MILKY WAY')")
#5
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1054','TAURUS','-6','6500','II','MILKY WAY')")
#6
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1181','CASSIOPEIA','0','8500','---','MILKY WAY')")
#7
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1572','CASSIOPEIA','-4.0','8000','la','MILKY WAY')")
#8
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('KEPLER_SUPERNOVA','OPHIUCHUS','-3','14000','la','MILKY WAY')")
#9
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('CAS A_C.1680','CASSIOPEIA','+5','9000','IIB','MILK WAY')")
#10
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('G1.9+0.3_CAL.1868','SAGITTARIUS','---','25000','la','MILKY WAY')")
#11
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1885A','ANDROMEDA','+5.85','2500000','IPEC','ANDROMEDA GALAXY')")
#12
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1895B','CENTAURUS','+8.0','10900000','la','NGC5253')")
#13
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1937C','CANES VENATICI','+8.4','13000000','la','IC 4182')")
#14
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1939C','CEPHEUS','+13','25200000','I','FIREWORKS GALAXY')")
#15
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1940B','COMA BERENICES','+12.8','38000000','II-P','NGC 4725')")
#16
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1961V','PERSEUS','+12.5','30000000','II?','NGC 1058')")
#17
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1972E','CENTAURUS','+8.7','10900000','la','NGC 5253')")
#18
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1983N','HYDRA','+11.8','15000000','IB','MESSIER 83')")
#19
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1986J','ANDROMEDA','+18.4','30000000','IIN','NGC 891')")
#20
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1987A','DORADO','+2.9','160000','IIPEC','LARGE MAGELLANIC CLOUD')")
#21
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1993J','URSA MAJOR','+10.7','11000000','IIB','M81')")
#22
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1994D','VIRGO','+15.2','50000000','la','NGC 4526')")
#23
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1998BW','TELESCOPIUM','?','140000000','LC','ESO 184-G82')")
#24
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 1999EH','LYNX','+18.3/-0.3','84000000','I','NGC 2770')")
#25
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2002BJ','LUPUS','+14.7','160000000','IIN','NGC 1821')")
#26
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2003FG','BOOTES','---','4000000000','la','ANONYMOUS GALAXY')")
#27
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2004DJ','CAMELOPARDALIS','---','8000000','II-P','NGC 2403')")
#28
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2005AP','COMA BERENICES','---','4700000000','II','?')")
#29
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2005GJ','CETUS','---','865000000','la/II-N','?')")
#30
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2005GL','PISCES','+16.5','200000000','II-N','NGC 266')")
#31
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2006GY','PERSEUS','+15','240000000','IIN','NGC 1260')")
#32
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2007BI','VIRGO','+18.3','---','la','ANONYMOUS DRAWF GALAXY')")
#33
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2007UY','LYNX','+16.8','84000000','IBC','NGC 2770')")
#34
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2008D','LYNX','---','88000000','lbc','NGC 2770')")
#35
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('MENeac Abell399.3.14.0','ARIES','+28.7','1000000000 (z=0.0613)','la','RED GLOBULAR CLUSTER')")
#36
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2009ip','PISCIS AUSTRINUS','---','66000000','lln','NGC 7259')")
#37
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2010lt','CAMELOPARDALIS','+17.0','240000000','la(SUB-LUMINOUS)','UGC 3378')")
#38
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2011fe','URSA MAJOR','+10.0','21000000','Ia','M101')")
#39
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2014J','URSA MAJOR','+10.5','11500000','Ia','M82')")
#40
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('ASASSN-15lh SN 2015L','INDUS','+16.9','3800000000','Ic','APMUKS(BJ) B215839.70-615403.9')")
#41
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('IPTF14hls','URSA MAJOR','+17.7','509000000','UNKNOWN','SDSS J092034.44+504148.7')")
#42
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2016aps','DRACO','+18.11','3600000000','SLSB-II','---')")
#43
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2018zd','CAMELOPARDALIS','+17.8','70000000','Ia-csm','NGC 2146')")
#44
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2019hgp','BOOTES','+20.16','920000000','Icn','---')")
#45
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2020fqv','VIRGO','+19.0','59400000','IIb','NGC 4568')")
#46
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2020tif','BOOTES','+15.89','120000000','IIn','NGC 5731')")
#47
  mycursor.execute("INSERT IGNORE INTO SUPERNOVAS (SUPERNOVA_DESIGNATION, CONSTELLATION_NAME, APPARENT_MAGNITUDE, DISTANCE_IN_LIGHTYEARS, TYPE, GALAXY)\
        VALUES ('SN 2023ixf','URSA MAJOR','+10.8','21000000','TYPE II-L','PINWHEEL GALAXY')")

  mydb.commit()

#END........